### ISSUE TITLE
Add Help menu to Algotaurus menu which opens this webpage

### ISSUE THREAD

**Issue by krajcsi** [AlgoTaurus/algotaurus#31]
https://github.com/krajcsi/algotaurus

**Comment by krajcsi** [comment]
And a link in the About dialog would be handy, too.

**Comment by markojaadam** [comment]
I guess the link opened with help command should directly open the README.md:
https://github.com/krajcsi/algotaurus/blob/master/README.md

**Comment by markojaadam** [comment]
To insert a link into the about window we have to replace the tkmessagebox instance inside the about_command function with a new toplevel window (eg. http://stackoverflow.com/questions/23482748/how-to-create-a-hyperlink-with-a-label-in-tkinter).
It is not too hard but I have to rewrite the entire function. Does this modification lead to an increased usability beside the help command?

In addition: To solve #12 previously I created an AlgoTaurusMessageBox class (approximately 60 rows long code). This class builds highly customizable popup window in comparison with tkMessageBox, therefore it could help with this about-window-with-hyperlink problem too. For that reason I think we should connect this feature to #12 instead of #31 (this issue).

**Comment by krajcsi** [comment]
Current solution (Help command in AT menu) is OK, no need to further changes in the About window.
